#!/usr/bin/env python3
"""
Manual benchmark analyzer.

This script reads a manifest generated by run-manual-benchmark-macos.sh and
estimates display latency from screen recordings by OCR'ing a server-side
timestamp overlay (SERVER_EPOCH_MS=<epoch_ms>).
"""

from __future__ import annotations

import argparse
import csv
import math
import re
import statistics
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

try:
    import cv2  # type: ignore
    import pytesseract  # type: ignore
except ImportError as exc:  # pragma: no cover - runtime dependency
    raise SystemExit(
        "Missing dependency. Install with: pip install opencv-python pytesseract"
    ) from exc


TIMESTAMP_PATTERN = re.compile(r"SERVER_EPOCH_MS[= :]*([0-9]{10,16})")
FALLBACK_DIGIT_PATTERN = re.compile(r"([0-9]{12,16})")


@dataclass(frozen=True)
class ManifestRow:
    protocol: str
    trial: str
    recording_start_epoch_ms: int
    recording_path: Path
    note: str


@dataclass(frozen=True)
class Sample:
    protocol: str
    trial: str
    frame_index: int
    frame_pos_ms: int
    recording_start_epoch_ms: int
    local_epoch_ms: int
    server_epoch_ms: int
    latency_ms: int
    recording_path: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", required=True, help="Path to manifest CSV.")
    parser.add_argument("--output-dir", required=True, help="Output directory path.")
    parser.add_argument(
        "--roi",
        default="140,320,1000,120",
        help="ROI in x,y,width,height. Default: 140,320,1000,120",
    )
    parser.add_argument(
        "--sample-every",
        type=int,
        default=1,
        help="Read every Nth frame. Default: 1",
    )
    parser.add_argument(
        "--max-latency-ms",
        type=int,
        default=2000,
        help="Discard outliers larger than this value. Default: 2000",
    )
    parser.add_argument(
        "--min-latency-ms",
        type=int,
        default=0,
        help="Discard outliers smaller than this value. Default: 0",
    )
    return parser.parse_args()


def parse_roi(value: str) -> tuple[int, int, int, int]:
    parts = value.split(",")
    if len(parts) != 4:
        raise ValueError("--roi must be x,y,width,height")
    x, y, w, h = (int(v) for v in parts)
    if x < 0 or y < 0 or w <= 0 or h <= 0:
        raise ValueError("ROI values must be positive and width/height > 0")
    return x, y, w, h


def read_manifest(path: Path) -> list[ManifestRow]:
    rows: list[ManifestRow] = []
    with path.open("r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        required = {
            "protocol",
            "trial",
            "recording_start_epoch_ms",
            "recording_path",
            "note",
        }
        if set(reader.fieldnames or []) != required:
            raise ValueError(
                f"Unexpected headers: {reader.fieldnames}. Required: {sorted(required)}"
            )

        for row in reader:
            recording_path = Path(row["recording_path"]).expanduser().resolve()
            rows.append(
                ManifestRow(
                    protocol=row["protocol"],
                    trial=row["trial"],
                    recording_start_epoch_ms=int(row["recording_start_epoch_ms"]),
                    recording_path=recording_path,
                    note=row["note"],
                )
            )
    return rows


def extract_server_epoch_ms(ocr_text: str) -> int | None:
    match = TIMESTAMP_PATTERN.search(ocr_text)
    if match:
        return int(match.group(1))

    fallback = FALLBACK_DIGIT_PATTERN.search(ocr_text)
    if fallback:
        return int(fallback.group(1))
    return None


def percentile(values: list[int], p: float) -> float:
    if not values:
        return float("nan")
    sorted_values = sorted(values)
    rank = max(0, min(len(sorted_values) - 1, math.ceil(len(sorted_values) * p) - 1))
    return float(sorted_values[rank])


def iter_samples(
    row: ManifestRow,
    roi: tuple[int, int, int, int],
    sample_every: int,
    min_latency_ms: int,
    max_latency_ms: int,
) -> Iterable[Sample]:
    capture = cv2.VideoCapture(str(row.recording_path))
    if not capture.isOpened():
        raise RuntimeError(f"Cannot open recording file: {row.recording_path}")

    x, y, w, h = roi
    frame_idx = 0
    try:
        while True:
            ok, frame = capture.read()
            if not ok:
                break

            if frame_idx % sample_every != 0:
                frame_idx += 1
                continue

            frame_pos_ms = int(capture.get(cv2.CAP_PROP_POS_MSEC))

            cropped = frame[y : y + h, x : x + w]
            gray = cv2.cvtColor(cropped, cv2.COLOR_BGR2GRAY)
            _, binary = cv2.threshold(
                gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU
            )
            ocr_text = pytesseract.image_to_string(
                binary,
                config="--psm 7 -c tessedit_char_whitelist=SERVER_EPOCH_MS=0123456789FRAME",
            )

            server_epoch_ms = extract_server_epoch_ms(ocr_text)
            if server_epoch_ms is None:
                frame_idx += 1
                continue

            local_epoch_ms = row.recording_start_epoch_ms + frame_pos_ms
            latency_ms = local_epoch_ms - server_epoch_ms
            if latency_ms < min_latency_ms or latency_ms > max_latency_ms:
                frame_idx += 1
                continue

            yield Sample(
                protocol=row.protocol,
                trial=row.trial,
                frame_index=frame_idx,
                frame_pos_ms=frame_pos_ms,
                recording_start_epoch_ms=row.recording_start_epoch_ms,
                local_epoch_ms=local_epoch_ms,
                server_epoch_ms=server_epoch_ms,
                latency_ms=latency_ms,
                recording_path=str(row.recording_path),
            )
            frame_idx += 1
    finally:
        capture.release()


def write_samples(path: Path, samples: list[Sample]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(
            [
                "protocol",
                "trial",
                "frame_index",
                "frame_pos_ms",
                "recording_start_epoch_ms",
                "local_epoch_ms",
                "server_epoch_ms",
                "latency_ms",
                "recording_path",
            ]
        )
        for sample in samples:
            writer.writerow(
                [
                    sample.protocol,
                    sample.trial,
                    sample.frame_index,
                    sample.frame_pos_ms,
                    sample.recording_start_epoch_ms,
                    sample.local_epoch_ms,
                    sample.server_epoch_ms,
                    sample.latency_ms,
                    sample.recording_path,
                ]
            )


def write_summary(path: Path, samples: list[Sample]) -> None:
    by_trial: dict[tuple[str, str], list[int]] = {}
    for sample in samples:
        by_trial.setdefault((sample.protocol, sample.trial), []).append(sample.latency_ms)

    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(
            ["protocol", "trial", "count", "median_ms", "p95_ms", "stddev_ms", "min_ms", "max_ms"]
        )
        for (protocol, trial), latency_values in sorted(by_trial.items()):
            if len(latency_values) < 2:
                stddev = 0.0
            else:
                stddev = statistics.pstdev(latency_values)
            writer.writerow(
                [
                    protocol,
                    trial,
                    len(latency_values),
                    statistics.median(latency_values),
                    percentile(latency_values, 0.95),
                    round(stddev, 3),
                    min(latency_values),
                    max(latency_values),
                ]
            )


def main() -> int:
    args = parse_args()
    roi = parse_roi(args.roi)
    manifest = Path(args.manifest).expanduser().resolve()
    output_dir = Path(args.output_dir).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    rows = read_manifest(manifest)
    if not rows:
        raise RuntimeError("Manifest is empty.")

    all_samples: list[Sample] = []
    for row in rows:
        if not row.recording_path.exists():
            raise RuntimeError(f"Recording file does not exist: {row.recording_path}")
        samples = list(
            iter_samples(
                row=row,
                roi=roi,
                sample_every=max(1, args.sample_every),
                min_latency_ms=args.min_latency_ms,
                max_latency_ms=args.max_latency_ms,
            )
        )
        all_samples.extend(samples)
        print(
            f"[{row.protocol} trial={row.trial}] extracted_samples={len(samples)} file={row.recording_path}"
        )

    if not all_samples:
        raise RuntimeError("No valid samples were extracted. Adjust ROI or recordings.")

    samples_csv = output_dir / "latency-samples.csv"
    summary_csv = output_dir / "latency-summary.csv"
    write_samples(samples_csv, all_samples)
    write_summary(summary_csv, all_samples)

    print(f"Wrote samples: {samples_csv}")
    print(f"Wrote summary: {summary_csv}")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as exc:  # pragma: no cover - CLI error path
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)
